import type { JsonValue } from "@bufbuild/protobuf";
import * as Y from "yjs";
import {
  allBlockRoomLocaleValueTargets,
  blockRoomLocaleValueIsEncoded,
  markBlockRoomLocaleValuePresent,
} from "./locale-presence.ts";
import {
  blockRoomBaseNodes,
  blockRoomLocaleOverlay,
  type CanonicalBlockRoomSnapshot,
} from "./materialization.ts";
import { applyPayloadRootDiff } from "./replay-payload.ts";
import {
  currentNodeType,
  insertLocaleNode,
  nodeMap,
  sameNodeType,
  sameValue,
} from "./replay-structure.ts";
import { fail } from "./internal.ts";

interface LocaleIntentTarget {
  target: ReturnType<typeof allBlockRoomLocaleValueTargets>[number];
}

function jsonObject(
  value: JsonValue | undefined,
): Record<string, JsonValue> | undefined {
  return value === undefined ? undefined : (value as Record<string, JsonValue>);
}

function targetPath(
  target: LocaleIntentTarget["target"],
): Array<readonly ["field" | "item", string]> {
  return target.path.map(({ selector }) => {
    if (selector.case === "fieldHandle")
      return ["field", selector.value] as const;
    // Locale targets are generated by allBlockRoomLocaleValueTargets from
    // canonical field/item handles, so the only other selector is itemHandle.
    return ["item", selector.value as string] as const;
  });
}

function rawLocaleValue(
  snapshot: CanonicalBlockRoomSnapshot,
  target: LocaleIntentTarget["target"],
): JsonValue | undefined {
  const ownerId = target.owner.value as string;
  const overlay = snapshot.localeOverlay.find((node) => node.id === ownerId);
  if (!overlay) return undefined;
  const payload = jsonObject(overlay.payload)!;
  const path = targetPath(target);
  if (overlay.family === "rich_text") {
    if (target.fieldHandle === "content") return payload.content;
    if (target.fieldHandle === "tableContent") {
      const rows = jsonObject(payload.content)!.rows as JsonValue[];
      const row = rows.find(
        (candidate) => jsonObject(candidate)!.rowId === path[1]?.[1],
      );
      if (row === undefined) return undefined;
      const cells = jsonObject(row)!.cells as JsonValue[];
      const cell = cells.find(
        (candidate) => jsonObject(candidate)!.cellId === path[3]?.[1],
      );
      if (cell === undefined) return undefined;
      return jsonObject(cell)!.content;
    }
    return jsonObject(payload.props)?.[target.fieldHandle];
  }
  if (path[0]?.[1] === "props") return jsonObject(payload.props)?.[path[1]![1]];
  const units = payload.units as JsonValue[];
  const unit = units.find(
    (candidate) => jsonObject(candidate)!.unitId === path[1]![1],
  );
  if (unit === undefined) return undefined;
  return jsonObject(jsonObject(unit)!.props)?.[path[3]![1]];
}

function changedLocaleIntentTargets(
  document: Y.Doc,
  before: CanonicalBlockRoomSnapshot,
  after: CanonicalBlockRoomSnapshot,
): LocaleIntentTarget[] {
  const oldNodes = nodeMap(before.localeOverlay);
  const nextNodes = nodeMap(after.localeOverlay);
  const changedNodeIds = new Set<string>();
  for (const id of new Set([...oldNodes.keys(), ...nextNodes.keys()])) {
    const oldNode = oldNodes.get(id);
    const nextNode = nextNodes.get(id);
    if (
      !oldNode ||
      !nextNode ||
      !sameNodeType(oldNode, nextNode) ||
      !sameValue(oldNode.payload, nextNode.payload)
    )
      changedNodeIds.add(id);
  }
  if (changedNodeIds.size === 0) return [];
  const changed: LocaleIntentTarget[] = [];
  for (const target of allBlockRoomLocaleValueTargets(document)) {
    if (!changedNodeIds.has(target.owner.value as string)) continue;
    const nextValue = rawLocaleValue(after, target);
    const oldValue = rawLocaleValue(before, target);
    if (
      !sameValue(oldValue, nextValue) &&
      blockRoomLocaleValueIsEncoded(document, target)
    )
      changed.push({ target });
  }
  return changed;
}

export function applyLocaleAdditions(
  document: Y.Doc,
  before: CanonicalBlockRoomSnapshot,
  after: CanonicalBlockRoomSnapshot,
  isTarget: boolean,
): void {
  // Canonical source rooms add shared base nodes and their locale projections
  // together. Target rooms cannot add base nodes (replay.ts checks parity).
  if (isTarget) return;

  const beforeLocale = nodeMap(before.localeOverlay);
  const afterLocale = nodeMap(after.localeOverlay);
  const newlyAddedLocaleIds = new Set(
    [...afterLocale.keys()].filter((id) => !beforeLocale.has(id)),
  );
  for (const id of afterLocale.keys()) {
    if (beforeLocale.has(id)) continue;
    // Base insertion may have been skipped because a peer deleted an observed
    // ancestor. Keep that subtree absent in both projections.
    if (!blockRoomBaseNodes(document).has(id)) continue;
    if (blockRoomLocaleOverlay(document).has(id)) {
      newlyAddedLocaleIds.delete(id);
    }
  }
  const localeAdds = [...newlyAddedLocaleIds]
    .map((id) => afterLocale.get(id)!)
    .sort(
      (left, right) =>
        (left.family === "page_section" ? 0 : 1) -
        (right.family === "page_section" ? 0 : 1),
    );
  for (const node of localeAdds) {
    // Inserting a Page section can include all newly-added descendant locale
    // nodes, so a later entry in this same pass may already be resident.
    if (blockRoomLocaleOverlay(document).has(node.id)) continue;
    insertLocaleNode(document, after, node, newlyAddedLocaleIds);
  }
}

export function applyLocaleChanges(
  document: Y.Doc,
  before: CanonicalBlockRoomSnapshot,
  after: CanonicalBlockRoomSnapshot,
): void {
  const beforeLocale = nodeMap(before.localeOverlay);
  const afterLocale = nodeMap(after.localeOverlay);
  const currentBaseIds = new Set(blockRoomBaseNodes(document).keys());
  // Canonical snapshots have one locale overlay per base node. Source base
  // deletion already removes that projection; target snapshots cannot delete
  // it without changing the base, which replay.ts rejects.

  for (const [id, oldNode] of beforeLocale) {
    const next = afterLocale.get(id);
    if (!next || sameValue(oldNode.payload, next.payload)) continue;
    if (!currentBaseIds.has(id)) continue;
    const existing = currentNodeType(blockRoomLocaleOverlay(document), id)!;
    if (!sameNodeType(existing, oldNode) || !sameNodeType(next, oldNode))
      fail(`replay:kind_changed:${id}`);
    applyPayloadRootDiff(
      document,
      { id, family: oldNode.family, locale: true },
      oldNode.payload,
      next.payload,
    );
  }

  for (const { target } of changedLocaleIntentTargets(document, before, after))
    markBlockRoomLocaleValuePresent(document, target);
}
